"alacritty" = "ï„ "
"github" = "ï„“"
"rust" = "î¨"
"private browsing" = "ïˆ›"
"firefox" = "ï‰©"
"file manager" = "ï¼"
"transmission" = "ï€™"
"mpv" = "ïœª"
"music" = "ï€"
"librewolf" = "ï’ˆ"

[other]
fallback_icon = "ğŸ¤¨"
deduplicate_icons = false
